services:

  frontend:
    build: frontend
    ports:
      - 20080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  backend:
    build: backend
    ports:
      - 21080:80
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app

  pgsql:
   image: postgres:9.5
   ports:
     - 22080:5432
   environment:
     - POSTGRES_DB=yii2advanced
     - POSTGRES_USER=yii2advanced
     - POSTGRES_PASSWORD=secret